# Generated by Django 4.2.2 on 2023-06-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='decto',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
